// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbqdhrzcbaesosjcnjfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicWRocnpjYmFlc29zamNuamZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTQ3MzYsImV4cCI6MjA2MDU5MDczNn0.foDz1Q9LWqT51Lz-DfcppPB3DFD72CiHX5F8CEQ9if8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);